default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>

development:
  <<: *default
  database: saas_app_development

  queue:
    <<: *default
    database: saas_app_development

test:
  <<: *default
  database: saas_app_test

  queue:
    <<: *default
    database: saas_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
